version: '3.3'

services:
  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/main.py
    command: python3 main.py
    env_file: .env
    depends_on:
      - postgres
